import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Mantis",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <div style={{ display: "grid", gridTemplateColumns: "0.4fr 1fr" }}>
        <div>SideBar</div>

        <div> {children}</div>
      </div>
    </main>
  );
}
