import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Mantis",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <div className={"main-container"}>
        <div style={{ display: "grid", gridTemplateColumns: "0.2fr 1fr" }}>
          <div>FIlters</div>
          <div>{children}</div>
        </div>
      </div>
    </main>
  );
}
