import type { Metadata } from "next";
import { Jura } from "next/font/google";
import "@/styles/globals.css";
import "@/styles/normalize.css";
import Footer from "@/layouts/footer/footer";
import Header from "@/layouts/header/header";
import "swiper/css";
import { getSiteMenu } from "@/api/site-menu/site-menu";
import qs from "qs";
export const metadata: Metadata = {
  title: "Mantis",
  description: "Generated by create next app",
};

const jura = Jura({ subsets: ["cyrillic"], weight: ["700", "400", "600"] });

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const siteMenuQwery = qs.stringify({
    populate: {
      MenuBLocks: {
        populate: "*",
      },
    },
  });

  const { data } = await getSiteMenu(siteMenuQwery);

  return (
    <html lang="ru">
      <body className={jura.className}>
        <Header menu_list={data.MenuBLocks} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
