import type { Metadata } from "next";
import { Jura } from "next/font/google";
import "@/styles/globals.css";
import "@/styles/normalize.css";

export const metadata: Metadata = {
  title: "Mantis",
  description: "Generated by create next app",
};

const jura = Jura({ subsets: ["cyrillic"], weight: ["700", "400", "600"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={jura.className}>{children}</body>
    </html>
  );
}
